Repository Damso-ForSmoker/Damso-iOS, pull requests merged in 2023-02, with the labels that each got.

#22 Revert "[Scene] -#8 내정보 화면 구성 및 작성"
  Damso.xcodeproj/project.pbxproj
  Damso/Global/Resources/Assets.xcassets/Vector.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/Vector.imageset/Vector.png
  Damso/Global/Resources/Assets.xcassets/Vector.imageset/Vector@2x.png
  Damso/Global/Resources/Assets.xcassets/Vector.imageset/Vector@3x.png
  Damso/Global/Resources/Assets.xcassets/alert-circle.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/alert-circle.imageset/alert-circle.png
  Damso/Global/Resources/Assets.xcassets/alert-circle.imageset/alert-circle@2x.png
  Damso/Global/Resources/Assets.xcassets/alert-circle.imageset/alert-circle@3x.png
  Damso/Global/Resources/Assets.xcassets/apple.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/apple.imageset/apple.png
  Damso/Global/Resources/Assets.xcassets/apple.imageset/apple@2x.png
  Damso/Global/Resources/Assets.xcassets/apple.imageset/apple@3x.png
  Damso/Global/Resources/Assets.xcassets/back.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/back.imageset/Vector.png
  Damso/Global/Resources/Assets.xcassets/back.imageset/Vector@2x.png
  Damso/Global/Resources/Assets.xcassets/back.imageset/Vector@3x.png
  Damso/Global/Resources/Assets.xcassets/chevron-right.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/chevron-right.imageset/chevron-right.png
  Damso/Global/Resources/Assets.xcassets/chevron-right.imageset/chevron-right@2x.png
  Damso/Global/Resources/Assets.xcassets/chevron-right.imageset/chevron-right@3x.png
  Damso/Global/Resources/Assets.xcassets/kakao.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/kakao.imageset/Frame 28.png
  Damso/Global/Resources/Assets.xcassets/kakao.imageset/Frame 28@2x.png
  Damso/Global/Resources/Assets.xcassets/kakao.imageset/Frame 28@3x.png
  Damso/Global/Resources/Assets.xcassets/logo.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/logo.imageset/logo 1.png
  Damso/Global/Resources/Assets.xcassets/logo.imageset/logo 1@2x.png
  Damso/Global/Resources/Assets.xcassets/logo.imageset/logo 1@3x.png
  Damso/Global/Resources/Assets.xcassets/naver.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/naver.imageset/Ellipse 18.png
  Damso/Global/Resources/Assets.xcassets/naver.imageset/Ellipse 18@2x.png
  Damso/Global/Resources/Assets.xcassets/naver.imageset/Ellipse 18@3x.png
  Damso/Global/Resources/Assets.xcassets/pencil.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/pencil.imageset/Group 91.png
  Damso/Global/Resources/Assets.xcassets/pencil.imageset/Group 91@2x.png
  Damso/Global/Resources/Assets.xcassets/pencil.imageset/Group 91@3x.png
  Damso/Global/Resources/Assets.xcassets/profile.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/profile.imageset/Group 77.png
  Damso/Global/Resources/Assets.xcassets/profile.imageset/Group 77@2x.png
  Damso/Global/Resources/Assets.xcassets/profile.imageset/Group 77@3x.png
  Damso/Info.plist
Labels: 🐙무너/정호, 🐞Fix

#27 Scene/#25 각 화면 연동 및 연결
  Damso.xcodeproj/project.pbxproj
  Damso/App/SceneDelegate.swift
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Damso/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Damso/Global/Resources/Assets.xcassets/HomeIcon.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/HomeIcon.imageset/IconView-1.svg
  Damso/Global/Resources/Assets.xcassets/HomeIconSelected.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/HomeIconSelected.imageset/IconView.svg
  Damso/Global/Resources/Assets.xcassets/SearchIcon.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/SearchIcon.imageset/Frame 19.svg
  Damso/Presentation/Input/Bookmark/BookmarkIsEmptyCell.swift
  Damso/Presentation/Input/Bookmark/BookmarkTableViewCell.swift
  Damso/Presentation/Input/Bookmark/BookmarkVC.swift
  Damso/Presentation/Input/Bookmark/BookmarkView.swift
  Damso/Presentation/Input/Location/ReportVC.swift
  Damso/Presentation/Input/Location/ReportView.swift
  Damso/Presentation/Input/information/ReportInputVC.swift
  Damso/Presentation/Input/information/ReportInputView.swift
  Damso/Presentation/Onboarding/OnboardingVC.swift
  Damso/Presentation/Onboarding/OnboardingView.swift
  Damso/Presentation/TabBar/TabBarController.swift
  Damso/Presentation/main/BottomSheetViewController.swift
  Damso/Presentation/main/FavoritesViewController.swift
  Damso/Presentation/main/Main.storyboard
  Damso/Presentation/main/MainViewController.swift
  Damso/Presentation/main/ProfileViewController.swift
Labels: 🐙무너/정호, 📱Scene

#29 Scene/#11 - 제보하기 화면 기능 추가
  .gitignore
  Damso.xcodeproj/project.pbxproj
  Damso.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Damso/App/AppDelegate.swift
  Damso/Data/Network/GeocodingManager.swift
  Damso/Data/Network/Keys.swift
  Damso/Data/Network/ReverseGCModel.swift
  Damso/Presentation/Bookmark/BookmarkIsEmptyCell.swift
  Damso/Presentation/Bookmark/BookmarkTableViewCell.swift
  Damso/Presentation/Bookmark/BookmarkVC.swift
  Damso/Presentation/Bookmark/BookmarkView.swift
  Damso/Presentation/Input/Inputinformation/ReportInputVC.swift
  Damso/Presentation/Input/Inputinformation/ReportInputView.swift
  Damso/Presentation/Input/Location/ReportVC.swift
  Damso/Presentation/Input/Location/ReportView.swift
Labels: 🐙무너/정호, 📱Scene, 🔨Feat

#30 [Refactor] - #28 API key 제거
  Damso/Data/Network/Keys.swift
Labels: 🐙무너/정호, 📌Refactor, ⚔️Remove

#31 Update README.md
  README.md
Labels: documentation, 🐙무너/정호

#34 [Scene] - #8 NaverThirdPartyLogin 헤더 내용 변경
  Pods/naveridlogin-sdk-ios/NaverThirdPartyLogin.xcframework/ios-arm64_armv7/NaverThirdPartyLogin.framework/Headers/NaverThirdPartyConstantsForApp.h
Labels: ☂️코비/유빈, 🐞Fix

#39 [Scene] - #17 Alamofire를 활용한 마커 가져오기 초안
  Damso/Data/Network/Markers.swift
  Damso/Data/Network/MarkersHTTPMethod.swift
  Damso/Presentation/main/MainViewController.swift
Labels: 🐙무너/정호, 📱Scene, 🔨Feat

#45 Scene/#15 - 주변 흡연구역 Search 파일 생성 및 구현
  Damso.xcodeproj/project.pbxproj
  Damso/Data/Network/MarkersHTTPMethod.swift
  Damso/Global/Resources/Assets.xcassets/AreaExactlyClosedImg.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/AreaExactlyClosedImg.imageset/ExactlyClosed 1x.png
  Damso/Global/Resources/Assets.xcassets/AreaExactlyClosedImg.imageset/ExactlyClosed 2x.png
  Damso/Global/Resources/Assets.xcassets/AreaExactlyClosedImg.imageset/ExactlyClosed 3x.png
  Damso/Global/Resources/Assets.xcassets/AreaExactlyOpenImg.imageset/AreaExactlyOpenImg 1x.png
  Damso/Global/Resources/Assets.xcassets/AreaExactlyOpenImg.imageset/AreaExactlyOpenImg 2x.png
  Damso/Global/Resources/Assets.xcassets/AreaExactlyOpenImg.imageset/AreaExactlyOpenImg 3x.png
  Damso/Global/Resources/Assets.xcassets/AreaExactlyOpenImg.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/AreaOpenImg.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/AreaOpenImg.imageset/Open 2x.png
  Damso/Global/Resources/Assets.xcassets/AreaOpenImg.imageset/Open 3x.png
  Damso/Global/Resources/Assets.xcassets/AreaOpenImg.imageset/OpenArea 1x.png
  Damso/Global/Resources/Assets.xcassets/AreaclosedImg.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/AreaclosedImg.imageset/close 1x.png
  Damso/Global/Resources/Assets.xcassets/AreaclosedImg.imageset/close 2x.png
  Damso/Global/Resources/Assets.xcassets/AreaclosedImg.imageset/close 3x.png
  Damso/Global/Resources/Assets.xcassets/CigaretteImg.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/CigaretteImg.imageset/ExactlyOpenArea 1x.png
  Damso/Global/Resources/Assets.xcassets/CigaretteImg.imageset/ExactlyOpenArea 2x.png
  Damso/Global/Resources/Assets.xcassets/CigaretteImg.imageset/ExactlyOpenArea 3x.png
  Damso/Global/Resources/Assets.xcassets/Vector.imageset/Vector.svg
  Damso/Presentation/Bookmark/BookmarkVC.swift
  Damso/Presentation/Bookmark/SmokingAreaTableViewCell.swift
  Damso/Presentation/Input/Location/ReportVC.swift
  Damso/Presentation/Search/SearchTypeVC.swift
  Damso/Presentation/Search/SearchTypeView.swift
  Damso/Presentation/Search/SearchVC.swift
  Damso/Presentation/Search/SearchView.swift
  Damso/Presentation/TabBar/TabBarController.swift
  Damso/Presentation/main/MainViewController.swift
Labels: 🐙무너/정호, 📱Scene

#48 Feat/#37 - 제보하기 화면 서버 연동 에러 처리 및 화면 수정
  Damso.xcodeproj/project.pbxproj
  Damso/Data/Network/ReportInput/ReportInputManager.swift
  Damso/Data/Network/ReportInput/ReportInputModel.swift
  Damso/Data/Network/ReportInput/ReportInputResult.swift
  Damso/Global/Resources/Assets.xcassets/DamsoTextLogo.imageset/Contents.json
  Damso/Global/Resources/Assets.xcassets/DamsoTextLogo.imageset/DamsoTextLogo 1x.png
  Damso/Global/Resources/Assets.xcassets/DamsoTextLogo.imageset/DamsoTextLogo 2x.png
  Damso/Global/Resources/Assets.xcassets/DamsoTextLogo.imageset/DamsoTextLogo 3x.png
  Damso/Global/Support/Base.lproj/LaunchScreen.storyboard
  Damso/Presentation/Input/Inputinformation/ReportInputVC.swift
  Damso/Presentation/Input/Inputinformation/ReportInputView.swift
  Damso/Presentation/Input/Location/ReportVC.swift
Labels: 🐙무너/정호, 📱Scene, 🔨Feat

#54 Feat/#37 - 서버 연동간 화면 정보 표시 자동화 및 서버 연동 에러처리
  Damso/Data/Network/ReportInput/ReportInputResult.swift
  Damso/Presentation/Input/Inputinformation/ReportInputVC.swift
  Damso/Presentation/main/BottomSheetViewController.swift
  Damso/Presentation/main/Main.storyboard
  Damso/Presentation/main/MainViewController.swift
Labels: 🐙무너/정호, 📱Scene, 🔨Feat

#63 [Refactor] - #28 Key값 숨기기
  Damso.xcodeproj/project.pbxproj
Labels: 🐙무너/정호, 📌Refactor
